name: IPFS Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: IPFS Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          echo "Deploying to IPFS"
          yarn
          yarn build
          touch .env
          echo IPFS_DEPLOY_PINATA__API_KEY=${{ secrets.PINATA_API_KEY }} >> .env
          echo IPFS_DEPLOY_PINATA__SECRET_API_KEY=${{ secrets.PINATA_API_SECRET }} >> .env
          echo IPFS_DEPLOY_CLOUDFLARE__API_EMAIL=${{ secrets.CF_API_EMAIL }} >> .env
          echo IPFS_DEPLOY_CLOUDFLARE__API_TOKEN=${{ secrets.CF_API_TOKEN }} >> .env
          echo IPFS_DEPLOY_CLOUDFLARE__ZONE=${{ secrets.CF_ZONE }} >> .env
          echo IPFS_DEPLOY_CLOUDFLARE__RECORD=${{ secrets.CF_RECORD }} >> .env
          npx ipfs-deploy build/ -p pinata -d cloudflare -C true -q
